version: "3.9"
services:
  web:
    build: docker/
    restart: on-failure:5
    ports:
      - 8004:80
    volumes:
      - ./:/app/Bookmarks

  db:
    image: mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "bookmarks"
    volumes:
      - ./docker/db/data:/var/lib/mysql